import { GenMapping, addMapping, toEncodedMap } from "@jridgewell/gen-mapping";
import { describe, expect, test } from "bun:test";
import { join } from "node:path";

import {
  attributeSourceMapBytes,
  summarizeBundledSources,
} from "../../src/dev/build-size-report.ts";

describe("build size report helpers", () => {
  test("attributes generated bytes to mapped sources", () => {
    const generated = "aaaabbbb\ncccc\n";
    const map = new GenMapping({ file: "bundle.js" });
    addMapping(map, {
      generated: { line: 1, column: 0 },
      source: "../src/a.ts",
      original: { line: 1, column: 0 },
    });
    addMapping(map, {
      generated: { line: 1, column: 4 },
      source: "../src/b.ts",
      original: { line: 1, column: 0 },
    });
    addMapping(map, {
      generated: { line: 2, column: 0 },
      source: "../node_modules/pkg/index.js",
      original: { line: 1, column: 0 },
    });

    const attribution = attributeSourceMapBytes(
      generated,
      toEncodedMap(map) as Parameters<typeof attributeSourceMapBytes>[1],
      join(process.cwd(), ".tmp", "bundle.js.map"),
    );

    expect(attribution.unmappedBytes).toBe(0);
    expect(Array.from(attribution.sourceBytes.entries())).toEqual([
      [join(process.cwd(), "src", "a.ts"), 4],
      [join(process.cwd(), "src", "b.ts"), 5],
      [join(process.cwd(), "node_modules", "pkg", "index.js"), 5],
    ]);
  });

  test("groups app and dependency bytes into logical units", () => {
    const repoRoot = process.cwd();
    const summary = summarizeBundledSources(
      {
        sourceBytes: new Map([
          [join(repoRoot, "src", "tui", "app.ts"), 1_500],
          [join(repoRoot, "src", "tui", "views.ts"), 500],
          [join(repoRoot, "src", "core", "service.ts"), 1_000],
          [join(repoRoot, "nanoboss.ts"), 300],
          [join(repoRoot, "node_modules", "highlight.js", "lib", "core.js"), 7_000],
          [join(repoRoot, "node_modules", "highlight.js", "lib", "languages", "typescript.js"), 3_000],
          [join(repoRoot, "node_modules", "typia", "lib", "index.js"), 1_200],
        ]),
        unmappedBytes: 200,
      },
      repoRoot,
      10,
    );

    expect(summary.appBytes).toBe(3_300);
    expect(summary.dependencyBytes).toBe(11_200);
    expect(summary.unmappedBytes).toBe(200);
    expect(summary.appGroups).toEqual([
      { label: "src/tui", bytes: 2_000 },
      { label: "src/core", bytes: 1_000 },
      { label: "entrypoints", bytes: 300 },
    ]);
    expect(summary.dependencyGroups).toEqual([
      { label: "highlight.js", bytes: 10_000 },
      { label: "typia", bytes: 1_200 },
    ]);
  });
});
